from .commands import (
    looks_like_local_access_refusal,
    parse_direct_gui_command,
    prompt_may_need_tools,
)
from .context_setup import (
    ContextToolPreparation,
    ExecutionPrerequisites,
    apply_tool_policy,
    load_execution_prerequisites,
    prepare_context_tools,
)
from .context_blocks import (
    build_live_pdf_context_prompt_block,
    build_live_web_context_prompt_block,
)
from .heuristics import (
    EMBEDDED_SEARCH_SOURCE,
    EMBEDDED_SEARCH_URL_TEMPLATE,
    build_extractive_summary,
    contains_hint,
    extract_web_urls,
    looks_like_knowledge_gap_response,
    looks_like_open_pdf_suggestion,
    looks_like_open_url_suggestion,
    looks_like_url_request,
    looks_like_web_access_refusal,
    prompt_may_need_mcp,
    should_attach_live_pdf_context,
    should_attach_live_web_context,
    topic_tokens,
)
from .fallbacks import (
    candidate_web_urls_for_prompt,
    extract_page_text_from_web_steps,
    try_browser_search_fallback,
    try_open_page_content_fallback,
    try_open_pdf_content_fallback,
    try_web_fetch_fallback,
)
from .paths import (
    build_pdf_search_roots,
    build_workspace_roots,
    extract_pdf_path_candidates,
    extract_video_path_candidates,
    find_video_by_basename_in_roots,
    list_available_pdfs_in_roots,
    resolve_pdf_path_for_roots,
    resolve_video_path_for_roots,
)
from .router import execute_direct_gui_command
from .runtime_flow import emit_agent_loop_result, maybe_handle_ollama_plain_mode
from .tool_registration import register_chat_gui_tools
from .tool_handlers_web_pdf import (
    pdf_find_sections,
    pdf_get_state,
    pdf_get_text,
    web_click,
    web_find_forms,
    web_get_dom_text,
    web_get_state,
    web_run_steps,
    web_scroll,
    web_type,
)
from .tool_handlers_openers import (
    extract_first_web_url,
    open_in_browser_tool,
    open_pdf_tool,
    open_url_tool,
)
from .tool_handlers_video import open_video_tool, resolve_video_path_for_gui_tool
from .tool_handlers_video_workflow import (
    label_behavior_segments_tool,
    segment_track_video_tool,
)
from .tool_handlers_chat_controls import (
    run_ai_text_segmentation_tool,
    select_annotation_model_tool,
    send_chat_prompt_tool,
    set_ai_text_prompt_tool,
    set_chat_model_tool,
    set_chat_prompt_tool,
    set_frame_tool,
    track_next_frames_tool,
)
from .tool_handlers_arxiv import (
    arxiv_search_tool,
    list_local_pdfs,
    safe_run_arxiv_search,
)
from .tool_handlers_citations import (
    add_citation_raw_tool,
    citation_fields_from_pdf_state,
    citation_fields_from_web_state,
    extract_doi,
    extract_year,
    list_citations_tool,
    normalize_citation_key,
    resolve_bib_output_path,
    save_citation_tool,
)
from .tool_handlers_filesystem import rename_file_tool
from .tool_handlers_realtime import (
    check_stream_source_tool,
    get_realtime_status_tool,
    list_realtime_logs_tool,
    list_realtime_models_tool,
    start_realtime_stream_tool,
    stop_realtime_stream_tool,
)
from .session_io import (
    emit_chunk,
    emit_final,
    emit_progress,
    load_history_messages,
    persist_turn,
)
from .provider_fallback import (
    format_provider_config_error,
    is_provider_config_error,
    is_provider_timeout_error,
    run_provider_fallback,
)
from .provider_runtime import (
    has_image_context,
    run_fast_mode,
    run_fast_provider_chat,
    run_gemini_provider_chat,
    run_ollama_chat,
    run_openai_chat,
)
from .provider_dependencies import format_dependency_error, provider_dependency_error
from .ollama_adapter import (
    build_gui_ollama_llm_callable,
    collect_gui_ollama_stream,
    extract_gui_ollama_text,
    format_gui_tool_trace,
    normalize_gui_messages_for_ollama,
    parse_gui_ollama_tool_calls,
)
from .runtime_config import (
    agent_loop_llm_timeout_seconds,
    agent_loop_tool_timeout_seconds,
    browser_first_for_web,
    fallback_retry_timeout_seconds,
    fallback_timeout_retry_seconds,
    fast_mode_timeout_seconds,
    ollama_agent_plain_timeout_seconds,
    ollama_agent_tool_timeout_seconds,
    ollama_plain_recovery_nudge_timeout_seconds,
    ollama_plain_recovery_timeout_seconds,
)
from .widget_bridge import (
    build_gui_context_payload,
    get_widget_action_result,
    invoke_widget_json_slot,
    invoke_widget_slot,
)
from .response_finalize import (
    apply_direct_gui_fallback,
    apply_empty_ollama_recovery,
    apply_pdf_response_fallback,
    apply_web_response_fallbacks,
    ensure_non_empty_final_text,
    should_apply_web_refusal_fallback,
)
from .telemetry import log_agent_result, log_runtime_timeouts, wrap_tool_callback
from .direct_commands import (
    execute_direct_gui_command as execute_direct_gui_command_flow,
    run_awaitable_sync,
)
from .prompt_builder import PromptBuildInputs, build_compact_system_prompt

__all__ = [
    "parse_direct_gui_command",
    "looks_like_local_access_refusal",
    "prompt_may_need_tools",
    "ExecutionPrerequisites",
    "ContextToolPreparation",
    "load_execution_prerequisites",
    "prepare_context_tools",
    "apply_tool_policy",
    "prompt_may_need_mcp",
    "contains_hint",
    "looks_like_url_request",
    "should_attach_live_web_context",
    "should_attach_live_pdf_context",
    "looks_like_web_access_refusal",
    "looks_like_knowledge_gap_response",
    "looks_like_open_url_suggestion",
    "looks_like_open_pdf_suggestion",
    "extract_web_urls",
    "build_extractive_summary",
    "topic_tokens",
    "candidate_web_urls_for_prompt",
    "try_web_fetch_fallback",
    "extract_page_text_from_web_steps",
    "try_browser_search_fallback",
    "try_open_page_content_fallback",
    "try_open_pdf_content_fallback",
    "EMBEDDED_SEARCH_URL_TEMPLATE",
    "EMBEDDED_SEARCH_SOURCE",
    "build_live_web_context_prompt_block",
    "build_live_pdf_context_prompt_block",
    "extract_pdf_path_candidates",
    "extract_video_path_candidates",
    "find_video_by_basename_in_roots",
    "build_workspace_roots",
    "build_pdf_search_roots",
    "resolve_pdf_path_for_roots",
    "resolve_video_path_for_roots",
    "list_available_pdfs_in_roots",
    "execute_direct_gui_command",
    "maybe_handle_ollama_plain_mode",
    "emit_agent_loop_result",
    "register_chat_gui_tools",
    "PromptBuildInputs",
    "build_compact_system_prompt",
    "web_get_dom_text",
    "web_get_state",
    "web_click",
    "web_type",
    "web_scroll",
    "web_find_forms",
    "web_run_steps",
    "pdf_get_state",
    "pdf_get_text",
    "pdf_find_sections",
    "extract_first_web_url",
    "open_url_tool",
    "open_in_browser_tool",
    "open_pdf_tool",
    "open_video_tool",
    "resolve_video_path_for_gui_tool",
    "segment_track_video_tool",
    "label_behavior_segments_tool",
    "set_frame_tool",
    "set_chat_prompt_tool",
    "send_chat_prompt_tool",
    "set_chat_model_tool",
    "select_annotation_model_tool",
    "track_next_frames_tool",
    "set_ai_text_prompt_tool",
    "run_ai_text_segmentation_tool",
    "arxiv_search_tool",
    "safe_run_arxiv_search",
    "list_local_pdfs",
    "extract_doi",
    "extract_year",
    "normalize_citation_key",
    "resolve_bib_output_path",
    "citation_fields_from_pdf_state",
    "citation_fields_from_web_state",
    "save_citation_tool",
    "add_citation_raw_tool",
    "list_citations_tool",
    "start_realtime_stream_tool",
    "stop_realtime_stream_tool",
    "get_realtime_status_tool",
    "list_realtime_models_tool",
    "list_realtime_logs_tool",
    "check_stream_source_tool",
    "rename_file_tool",
    "emit_chunk",
    "emit_progress",
    "emit_final",
    "load_history_messages",
    "persist_turn",
    "is_provider_config_error",
    "format_provider_config_error",
    "is_provider_timeout_error",
    "run_provider_fallback",
    "has_image_context",
    "run_fast_mode",
    "run_fast_provider_chat",
    "run_ollama_chat",
    "run_openai_chat",
    "run_gemini_provider_chat",
    "provider_dependency_error",
    "format_dependency_error",
    "build_gui_ollama_llm_callable",
    "collect_gui_ollama_stream",
    "parse_gui_ollama_tool_calls",
    "normalize_gui_messages_for_ollama",
    "extract_gui_ollama_text",
    "format_gui_tool_trace",
    "fast_mode_timeout_seconds",
    "agent_loop_llm_timeout_seconds",
    "ollama_agent_tool_timeout_seconds",
    "agent_loop_tool_timeout_seconds",
    "browser_first_for_web",
    "ollama_agent_plain_timeout_seconds",
    "ollama_plain_recovery_timeout_seconds",
    "ollama_plain_recovery_nudge_timeout_seconds",
    "fallback_retry_timeout_seconds",
    "fallback_timeout_retry_seconds",
    "invoke_widget_slot",
    "invoke_widget_json_slot",
    "get_widget_action_result",
    "build_gui_context_payload",
    "should_apply_web_refusal_fallback",
    "apply_pdf_response_fallback",
    "apply_empty_ollama_recovery",
    "ensure_non_empty_final_text",
    "apply_direct_gui_fallback",
    "apply_web_response_fallbacks",
    "log_runtime_timeouts",
    "log_agent_result",
    "wrap_tool_callback",
    "run_awaitable_sync",
    "execute_direct_gui_command_flow",
]
