"""Application services layer for Annolid."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "AgentPipelineRequest": "annolid.services.agent",
    "audit_agent_secrets": "annolid.services.agent_admin",
    "add_agent_feedback": "annolid.services.agent_workspace",
    "add_agent_cron_job": "annolid.services.agent_cron",
    "run_agent_acp_bridge": "annolid.services.agent_bridge",
    "build_agent_regression_eval": "annolid.services.agent_eval",
    "BehaviorTimeBudgetReport": "annolid.services.time_budget",
    "check_for_agent_update": "annolid.services.agent_update",
    "build_chat_pdf_search_roots": "annolid.services.chat_runtime",
    "build_chat_agent_loop": "annolid.services.chat_provider_runtime",
    "build_chat_gui_context_payload": "annolid.services.chat_widget_bridge",
    "capture_chat_web_screenshot": "annolid.services.chat_web_pdf",
    "clear_chat_session": "annolid.services.chat_session",
    "label_chat_behavior_segments_tool": "annolid.services.chat_video",
    "load_chat_execution_prerequisites": "annolid.services.chat_context",
    "build_chat_vcs_read_roots": "annolid.services.chat_runtime",
    "build_chat_workspace_roots": "annolid.services.chat_runtime",
    "EmbeddingSearchMatch": "annolid.services.embedding_search",
    "build_tracking_video_processor": "annolid.services.tracking",
    "build_yolo_dataset_from_index": "annolid.services.export",
    "compute_behavior_time_budget_report": "annolid.services.time_budget",
    "create_cutie_engine": "annolid.services.tracking",
    "create_segmented_cutie_executor": "annolid.services.tracking",
    "export_behavior_time_budget": "annolid.services.export",
    "export_labelme_json_to_csv": "annolid.services.export",
    "evaluate_agent_eval_gate": "annolid.services.agent_eval",
    "extract_chat_first_web_url": "annolid.services.chat_web_pdf",
    "extract_chat_web_structured": "annolid.services.chat_web_pdf",
    "format_chat_dependency_error": "annolid.services.chat_provider_runtime",
    "format_chat_provider_config_error": "annolid.services.chat_provider_runtime",
    "flush_agent_memory": "annolid.services.agent_workspace",
    "find_chat_pdf_sections": "annolid.services.chat_web_pdf",
    "find_chat_web_forms": "annolid.services.chat_web_pdf",
    "get_agent_status": "annolid.services.agent_cron",
    "get_chat_attachment_roots": "annolid.services.chat_runtime",
    "get_chat_allowed_read_roots": "annolid.services.chat_runtime",
    "get_chat_camera_snapshots_dir": "annolid.services.chat_runtime",
    "get_chat_email_defaults": "annolid.services.chat_runtime",
    "get_chat_session_store": "annolid.services.chat_session",
    "chat_agent_loop_llm_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_agent_loop_tool_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_browser_first_for_web": "annolid.services.chat_provider_runtime",
    "chat_fallback_retry_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_fallback_timeout_retry_seconds": "annolid.services.chat_provider_runtime",
    "chat_fast_mode_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_ollama_agent_plain_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_ollama_agent_tool_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_ollama_plain_recovery_nudge_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_ollama_plain_recovery_timeout_seconds": "annolid.services.chat_provider_runtime",
    "chat_provider_dependency_error": "annolid.services.chat_provider_runtime",
    "has_chat_image_context": "annolid.services.chat_provider_runtime",
    "get_chat_realtime_defaults": "annolid.services.chat_runtime",
    "get_chat_tutorials_dir": "annolid.services.chat_runtime",
    "get_chat_pdf_state": "annolid.services.chat_web_pdf",
    "get_chat_pdf_text": "annolid.services.chat_web_pdf",
    "get_chat_web_dom_text": "annolid.services.chat_web_pdf",
    "get_chat_web_state": "annolid.services.chat_web_pdf",
    "get_chat_workspace": "annolid.services.chat_runtime",
    "get_chat_widget_action_result": "annolid.services.chat_widget_bridge",
    "has_tracking_completion_artifacts": "annolid.services.tracking",
    "import_deeplabcut_dataset": "annolid.services.export",
    "inspect_agent_memory": "annolid.services.agent_workspace",
    "inspect_agent_skills": "annolid.services.agent_workspace",
    "is_cutie_model_name": "annolid.services.tracking",
    "list_agent_cron_jobs": "annolid.services.agent_cron",
    "onboard_agent_workspace": "annolid.services.agent_cron",
    "predict_behavior": "annolid.services.inference",
    "is_chat_provider_config_error": "annolid.services.chat_provider_runtime",
    "is_chat_provider_timeout_error": "annolid.services.chat_provider_runtime",
    "resolve_chat_provider_kind": "annolid.services.chat_provider_runtime",
    "resolve_tracking_video_processor_class": "annolid.services.tracking",
    "run_agent_pipeline": "annolid.services.agent",
    "run_agent_cron_job": "annolid.services.agent_cron",
    "run_agent_eval": "annolid.services.agent_eval",
    "run_agent_security_audit": "annolid.services.agent_admin",
    "run_agent_security_check": "annolid.services.agent_admin",
    "run_behavior_inference_cli": "annolid.services.inference",
    "run_behavior_training_cli": "annolid.services.training",
    "run_behavior_video_agent": "annolid.services.inference",
    "run_embedding_search": "annolid.services.embedding_search",
    "run_polygon_frame_training_cli": "annolid.services.training",
    "run_tracking_video_frames": "annolid.services.tracking",
    "run_video_processor_frames": "annolid.services.tracking",
    "search_indexed_frames": "annolid.services.search",
    "search_video_frames": "annolid.services.search",
    "set_agent_secret": "annolid.services.agent_admin",
    "set_agent_cron_job_enabled": "annolid.services.agent_cron",
    "shadow_agent_skills": "annolid.services.agent_workspace",
    "resolve_chat_pdf_path": "annolid.services.chat_runtime",
    "resolve_chat_video_path": "annolid.services.chat_runtime",
    "resolve_chat_video_path_for_gui_tool": "annolid.services.chat_video",
    "train_behavior_model": "annolid.services.training",
    "validate_behavior_model": "annolid.services.training",
    "remove_agent_secret": "annolid.services.agent_admin",
    "remove_agent_cron_job": "annolid.services.agent_cron",
    "migrate_agent_secrets": "annolid.services.agent_admin",
    "open_chat_in_browser_tool": "annolid.services.chat_web_pdf",
    "open_chat_pdf_tool": "annolid.services.chat_web_pdf",
    "open_chat_url_tool": "annolid.services.chat_web_pdf",
    "open_chat_video_tool": "annolid.services.chat_video",
    "refresh_agent_skills": "annolid.services.agent_workspace",
    "load_chat_history_messages": "annolid.services.chat_session",
    "invoke_chat_widget_json_slot": "annolid.services.chat_widget_bridge",
    "invoke_chat_widget_slot": "annolid.services.chat_widget_bridge",
    "read_chat_memory_text": "annolid.services.chat_runtime",
    "persist_chat_turn": "annolid.services.chat_session",
    "prepare_chat_context_tools": "annolid.services.chat_context",
    "register_chat_gui_toolset": "annolid.services.chat_context",
    "rollback_agent_update": "annolid.services.agent_update",
    "run_chat_awaitable_sync": "annolid.services.chat_widget_bridge",
    "run_chat_web_steps": "annolid.services.chat_web_pdf",
    "emit_chat_chunk": "annolid.services.chat_session",
    "emit_chat_final": "annolid.services.chat_session",
    "emit_chat_progress": "annolid.services.chat_session",
    "log_chat_runtime_timeouts": "annolid.services.chat_provider_runtime",
    "execute_chat_direct_gui_command": "annolid.services.chat_widget_bridge",
    "click_chat_web": "annolid.services.chat_web_pdf",
    "describe_chat_web_view": "annolid.services.chat_web_pdf",
    "run_chat_fast_mode": "annolid.services.chat_provider_runtime",
    "run_chat_fast_provider_chat": "annolid.services.chat_provider_runtime",
    "run_chat_gemini": "annolid.services.chat_provider_runtime",
    "run_chat_ollama": "annolid.services.chat_provider_runtime",
    "run_chat_openai": "annolid.services.chat_provider_runtime",
    "run_chat_provider_fallback": "annolid.services.chat_provider_runtime",
    "scroll_chat_web": "annolid.services.chat_web_pdf",
    "segment_track_chat_video_tool": "annolid.services.chat_video",
    "type_chat_web": "annolid.services.chat_web_pdf",
    "run_legacy_agent_update": "annolid.services.agent_update",
    "validate_agent_tools": "annolid.services.agent_tooling",
    "write_behavior_time_budget_report_csv": "annolid.services.time_budget",
    "run_agent_update": "annolid.services.agent_update",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    return getattr(module, name)
