from annolid.gui.widgets.extract_frame_dialog import ExtractFrameDialog
from annolid.gui.widgets.convert_coco_dialog import ConvertCOODialog
from annolid.gui.widgets.train_model_dialog import TrainModelDialog
from annolid.gui.widgets.track_dialog import TrackDialog
from annolid.gui.widgets.glitter2_dialog import Glitter2Dialog
from annolid.gui.widgets.progressing_dialog import ProgressingWindow
from annolid.gui.widgets.quality_control_dialog import QualityControlDialog
from annolid.gui.widgets.about_dialog import SystemInfoDialog
from annolid.gui.widgets.flags import FlagTableWidget
from annolid.gui.widgets.video_recording import RecordingWidget
from annolid.gui.widgets.screen_shot import CanvasScreenshotWidget
from annolid.gui.widgets.convert_deeplabcut_dialog import ConvertDLCDialog
from annolid.gui.widgets.realtime_control_widget import RealtimeControlWidget
